ts-node src/main addArtist --name 'Guasones' --country 'Argentina'
ts-node src/main addArtist --name 'Las Pastillas del Abuelo' --country 'Argentina'
ts-node src/main addArtist --name 'De la gran piñata' --country 'Uruguay'
ts-node src/main addArtist --name 'La Vela Puerca' --country 'Uruguay'
ts-node src/main addArtist --name 'El Kuelgue' --country 'Argentina'